// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: game.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PublicKey        string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature        string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	TelegramInitData string                 `protobuf:"bytes,4,opt,name=telegram_init_data,json=telegramInitData,proto3" json:"telegram_init_data,omitempty"` // raw initData from Telegram WebApp
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *LoginRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *LoginRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginRequest) GetTelegramInitData() string {
	if x != nil {
		return x.TelegramInitData
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GetHouseWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHouseWalletRequest) Reset() {
	*x = GetHouseWalletRequest{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHouseWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHouseWalletRequest) ProtoMessage() {}

func (x *GetHouseWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHouseWalletRequest.ProtoReflect.Descriptor instead.
func (*GetHouseWalletRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

type GetHouseWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseWallet   string                 `protobuf:"bytes,1,opt,name=house_wallet,json=houseWallet,proto3" json:"house_wallet,omitempty"` // Solana public key (base58)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHouseWalletResponse) Reset() {
	*x = GetHouseWalletResponse{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHouseWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHouseWalletResponse) ProtoMessage() {}

func (x *GetHouseWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHouseWalletResponse.ProtoReflect.Descriptor instead.
func (*GetHouseWalletResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *GetHouseWalletResponse) GetHouseWallet() string {
	if x != nil {
		return x.HouseWallet
	}
	return ""
}

type ConfirmDepositRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TxSig         string                 `protobuf:"bytes,2,opt,name=tx_sig,json=txSig,proto3" json:"tx_sig,omitempty"` // Solana transaction signature to verify on-chain
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmDepositRequest) Reset() {
	*x = ConfirmDepositRequest{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmDepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmDepositRequest) ProtoMessage() {}

func (x *ConfirmDepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmDepositRequest.ProtoReflect.Descriptor instead.
func (*ConfirmDepositRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmDepositRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConfirmDepositRequest) GetTxSig() string {
	if x != nil {
		return x.TxSig
	}
	return ""
}

type ConfirmDepositResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	PlayerId      string                 `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmDepositResponse) Reset() {
	*x = ConfirmDepositResponse{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmDepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmDepositResponse) ProtoMessage() {}

func (x *ConfirmDepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmDepositResponse.ProtoReflect.Descriptor instead.
func (*ConfirmDepositResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmDepositResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmDepositResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ConfirmDepositResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type AttackRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TargetPlayerId string                 `protobuf:"bytes,2,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AttackRequest) Reset() {
	*x = AttackRequest{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackRequest) ProtoMessage() {}

func (x *AttackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackRequest.ProtoReflect.Descriptor instead.
func (*AttackRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *AttackRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AttackRequest) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

type AttackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackResponse) Reset() {
	*x = AttackResponse{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackResponse) ProtoMessage() {}

func (x *AttackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackResponse.ProtoReflect.Descriptor instead.
func (*AttackResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *AttackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AttackResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CreateSessionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxPlayers      uint32                 `protobuf:"varint,1,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	EntryFee        float32                `protobuf:"fixed32,2,opt,name=entry_fee,json=entryFee,proto3" json:"entry_fee,omitempty"` // SOL
	DurationSeconds uint32                 `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	BotCount        uint32                 `protobuf:"varint,4,opt,name=bot_count,json=botCount,proto3" json:"bot_count,omitempty"` // number of AI bots to spawn (0–20)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *CreateSessionRequest) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *CreateSessionRequest) GetEntryFee() float32 {
	if x != nil {
		return x.EntryFee
	}
	return 0
}

func (x *CreateSessionRequest) GetDurationSeconds() uint32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *CreateSessionRequest) GetBotCount() uint32 {
	if x != nil {
		return x.BotCount
	}
	return 0
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SessionInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	HostId          string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	MaxPlayers      uint32                 `protobuf:"varint,3,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	CurrentPlayers  uint32                 `protobuf:"varint,4,opt,name=current_players,json=currentPlayers,proto3" json:"current_players,omitempty"`
	EntryFee        float32                `protobuf:"fixed32,5,opt,name=entry_fee,json=entryFee,proto3" json:"entry_fee,omitempty"`
	DurationSeconds uint32                 `protobuf:"varint,6,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // "waiting" | "in_progress" | "ended"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *SessionInfo) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *SessionInfo) GetCurrentPlayers() uint32 {
	if x != nil {
		return x.CurrentPlayers
	}
	return 0
}

func (x *SessionInfo) GetEntryFee() float32 {
	if x != nil {
		return x.EntryFee
	}
	return 0
}

func (x *SessionInfo) GetDurationSeconds() uint32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *SessionInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{11}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{12}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type JoinSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSessionRequest) Reset() {
	*x = JoinSessionRequest{}
	mi := &file_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSessionRequest) ProtoMessage() {}

func (x *JoinSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSessionRequest.ProtoReflect.Descriptor instead.
func (*JoinSessionRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{13}
}

func (x *JoinSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type JoinSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSessionResponse) Reset() {
	*x = JoinSessionResponse{}
	mi := &file_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSessionResponse) ProtoMessage() {}

func (x *JoinSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSessionResponse.ProtoReflect.Descriptor instead.
func (*JoinSessionResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{14}
}

func (x *JoinSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinSessionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StartGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{15}
}

func (x *StartGameRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StartGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameResponse) Reset() {
	*x = StartGameResponse{}
	mi := &file_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameResponse) ProtoMessage() {}

func (x *StartGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameResponse.ProtoReflect.Descriptor instead.
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{16}
}

func (x *StartGameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartGameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WatchLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchLobbyRequest) Reset() {
	*x = WatchLobbyRequest{}
	mi := &file_game_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchLobbyRequest) ProtoMessage() {}

func (x *WatchLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchLobbyRequest.ProtoReflect.Descriptor instead.
func (*WatchLobbyRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{17}
}

func (x *WatchLobbyRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type LobbyPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	IsHost        bool                   `protobuf:"varint,2,opt,name=is_host,json=isHost,proto3" json:"is_host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyPlayer) Reset() {
	*x = LobbyPlayer{}
	mi := &file_game_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyPlayer) ProtoMessage() {}

func (x *LobbyPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyPlayer.ProtoReflect.Descriptor instead.
func (*LobbyPlayer) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{18}
}

func (x *LobbyPlayer) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LobbyPlayer) GetIsHost() bool {
	if x != nil {
		return x.IsHost
	}
	return false
}

type LobbyUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Players         []*LobbyPlayer         `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	MaxPlayers      uint32                 `protobuf:"varint,3,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	EntryFee        float32                `protobuf:"fixed32,4,opt,name=entry_fee,json=entryFee,proto3" json:"entry_fee,omitempty"`
	DurationSeconds uint32                 `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	HostId          string                 `protobuf:"bytes,7,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LobbyUpdate) Reset() {
	*x = LobbyUpdate{}
	mi := &file_game_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyUpdate) ProtoMessage() {}

func (x *LobbyUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyUpdate.ProtoReflect.Descriptor instead.
func (*LobbyUpdate) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{19}
}

func (x *LobbyUpdate) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LobbyUpdate) GetPlayers() []*LobbyPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *LobbyUpdate) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *LobbyUpdate) GetEntryFee() float32 {
	if x != nil {
		return x.EntryFee
	}
	return 0
}

func (x *LobbyUpdate) GetDurationSeconds() uint32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *LobbyUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LobbyUpdate) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_game_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{20}
}

func (x *ConnectRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TargetX       float32                `protobuf:"fixed32,2,opt,name=target_x,json=targetX,proto3" json:"target_x,omitempty"`
	TargetY       float32                `protobuf:"fixed32,3,opt,name=target_y,json=targetY,proto3" json:"target_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_game_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{21}
}

func (x *MoveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MoveRequest) GetTargetX() float32 {
	if x != nil {
		return x.TargetX
	}
	return 0
}

func (x *MoveRequest) GetTargetY() float32 {
	if x != nil {
		return x.TargetY
	}
	return 0
}

type MoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_game_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{22}
}

func (x *MoveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MoveResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CollectLootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	LootId        string                 `protobuf:"bytes,2,opt,name=loot_id,json=lootId,proto3" json:"loot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectLootRequest) Reset() {
	*x = CollectLootRequest{}
	mi := &file_game_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectLootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectLootRequest) ProtoMessage() {}

func (x *CollectLootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectLootRequest.ProtoReflect.Descriptor instead.
func (*CollectLootRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{23}
}

func (x *CollectLootRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CollectLootRequest) GetLootId() string {
	if x != nil {
		return x.LootId
	}
	return ""
}

type CollectLootResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage        string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	NewEncryptedBalance string                 `protobuf:"bytes,3,opt,name=new_encrypted_balance,json=newEncryptedBalance,proto3" json:"new_encrypted_balance,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CollectLootResponse) Reset() {
	*x = CollectLootResponse{}
	mi := &file_game_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectLootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectLootResponse) ProtoMessage() {}

func (x *CollectLootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectLootResponse.ProtoReflect.Descriptor instead.
func (*CollectLootResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{24}
}

func (x *CollectLootResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CollectLootResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CollectLootResponse) GetNewEncryptedBalance() string {
	if x != nil {
		return x.NewEncryptedBalance
	}
	return ""
}

type GameStateUpdate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServerTime       int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	RemainingSeconds uint32                 `protobuf:"varint,3,opt,name=remaining_seconds,json=remainingSeconds,proto3" json:"remaining_seconds,omitempty"`
	Players          []*Player              `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	LootItems        []*LootItem            `protobuf:"bytes,5,rep,name=loot_items,json=lootItems,proto3" json:"loot_items,omitempty"`
	Npcs             []*NPC                 `protobuf:"bytes,6,rep,name=npcs,proto3" json:"npcs,omitempty"`
	Hazards          []*Hazard              `protobuf:"bytes,7,rep,name=hazards,proto3" json:"hazards,omitempty"`
	Events           []*GameEvent           `protobuf:"bytes,8,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GameStateUpdate) Reset() {
	*x = GameStateUpdate{}
	mi := &file_game_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateUpdate) ProtoMessage() {}

func (x *GameStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateUpdate.ProtoReflect.Descriptor instead.
func (*GameStateUpdate) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{25}
}

func (x *GameStateUpdate) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GameStateUpdate) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *GameStateUpdate) GetRemainingSeconds() uint32 {
	if x != nil {
		return x.RemainingSeconds
	}
	return 0
}

func (x *GameStateUpdate) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameStateUpdate) GetLootItems() []*LootItem {
	if x != nil {
		return x.LootItems
	}
	return nil
}

func (x *GameStateUpdate) GetNpcs() []*NPC {
	if x != nil {
		return x.Npcs
	}
	return nil
}

func (x *GameStateUpdate) GetHazards() []*Hazard {
	if x != nil {
		return x.Hazards
	}
	return nil
}

func (x *GameStateUpdate) GetEvents() []*GameEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	Health        int32                  `protobuf:"varint,5,opt,name=health,proto3" json:"health,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Kills         int32                  `protobuf:"varint,7,opt,name=kills,proto3" json:"kills,omitempty"`
	Treasure      int32                  `protobuf:"varint,8,opt,name=treasure,proto3" json:"treasure,omitempty"`
	CharacterIdx  uint32                 `protobuf:"varint,9,opt,name=character_idx,json=characterIdx,proto3" json:"character_idx,omitempty"` // 0-7: which character sprite to display
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_game_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{26}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Player) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Player) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Player) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Player) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Player) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *Player) GetTreasure() int32 {
	if x != nil {
		return x.Treasure
	}
	return 0
}

func (x *Player) GetCharacterIdx() uint32 {
	if x != nil {
		return x.CharacterIdx
	}
	return 0
}

type LootItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemType      string                 `protobuf:"bytes,2,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LootItem) Reset() {
	*x = LootItem{}
	mi := &file_game_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LootItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LootItem) ProtoMessage() {}

func (x *LootItem) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LootItem.ProtoReflect.Descriptor instead.
func (*LootItem) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{27}
}

func (x *LootItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LootItem) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *LootItem) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *LootItem) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *LootItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type NPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NpcType       string                 `protobuf:"bytes,2,opt,name=npc_type,json=npcType,proto3" json:"npc_type,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	Health        int32                  `protobuf:"varint,5,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NPC) Reset() {
	*x = NPC{}
	mi := &file_game_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NPC) ProtoMessage() {}

func (x *NPC) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NPC.ProtoReflect.Descriptor instead.
func (*NPC) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{28}
}

func (x *NPC) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NPC) GetNpcType() string {
	if x != nil {
		return x.NpcType
	}
	return ""
}

func (x *NPC) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *NPC) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *NPC) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

type Hazard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HazardType    string                 `protobuf:"bytes,2,opt,name=hazard_type,json=hazardType,proto3" json:"hazard_type,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	Radius        float32                `protobuf:"fixed32,5,opt,name=radius,proto3" json:"radius,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hazard) Reset() {
	*x = Hazard{}
	mi := &file_game_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hazard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hazard) ProtoMessage() {}

func (x *Hazard) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hazard.ProtoReflect.Descriptor instead.
func (*Hazard) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{29}
}

func (x *Hazard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hazard) GetHazardType() string {
	if x != nil {
		return x.HazardType
	}
	return ""
}

func (x *Hazard) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Hazard) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Hazard) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *Hazard) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GameEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_game_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{30}
}

func (x *GameEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *GameEvent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GameEvent) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *GameEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x04game\"\x93\x01\n" +
	"\fLoginRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12,\n" +
	"\x12telegram_init_data\x18\x04 \x01(\tR\x10telegramInitData\"O\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"\x17\n" +
	"\x15GetHouseWalletRequest\";\n" +
	"\x16GetHouseWalletResponse\x12!\n" +
	"\fhouse_wallet\x18\x01 \x01(\tR\vhouseWallet\"M\n" +
	"\x15ConfirmDepositRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06tx_sig\x18\x02 \x01(\tR\x05txSig\"e\n" +
	"\x16ConfirmDepositResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\tR\bplayerId\"X\n" +
	"\rAttackRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12(\n" +
	"\x10target_player_id\x18\x02 \x01(\tR\x0etargetPlayerId\"O\n" +
	"\x0eAttackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x9c\x01\n" +
	"\x14CreateSessionRequest\x12\x1f\n" +
	"\vmax_players\x18\x01 \x01(\rR\n" +
	"maxPlayers\x12\x1b\n" +
	"\tentry_fee\x18\x02 \x01(\x02R\bentryFee\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\rR\x0fdurationSeconds\x12\x1b\n" +
	"\tbot_count\x18\x04 \x01(\rR\bbotCount\"L\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xef\x01\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1f\n" +
	"\vmax_players\x18\x03 \x01(\rR\n" +
	"maxPlayers\x12'\n" +
	"\x0fcurrent_players\x18\x04 \x01(\rR\x0ecurrentPlayers\x12\x1b\n" +
	"\tentry_fee\x18\x05 \x01(\x02R\bentryFee\x12)\n" +
	"\x10duration_seconds\x18\x06 \x01(\rR\x0fdurationSeconds\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\x15\n" +
	"\x13ListSessionsRequest\"E\n" +
	"\x14ListSessionsResponse\x12-\n" +
	"\bsessions\x18\x01 \x03(\v2\x11.game.SessionInfoR\bsessions\"3\n" +
	"\x12JoinSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"E\n" +
	"\x13JoinSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"1\n" +
	"\x10StartGameRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"C\n" +
	"\x11StartGameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"2\n" +
	"\x11WatchLobbyRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"C\n" +
	"\vLobbyPlayer\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\ais_host\x18\x02 \x01(\bR\x06isHost\"\xf3\x01\n" +
	"\vLobbyUpdate\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12+\n" +
	"\aplayers\x18\x02 \x03(\v2\x11.game.LobbyPlayerR\aplayers\x12\x1f\n" +
	"\vmax_players\x18\x03 \x01(\rR\n" +
	"maxPlayers\x12\x1b\n" +
	"\tentry_fee\x18\x04 \x01(\x02R\bentryFee\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\rR\x0fdurationSeconds\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x17\n" +
	"\ahost_id\x18\a \x01(\tR\x06hostId\"/\n" +
	"\x0eConnectRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"b\n" +
	"\vMoveRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\btarget_x\x18\x02 \x01(\x02R\atargetX\x12\x19\n" +
	"\btarget_y\x18\x03 \x01(\x02R\atargetY\"M\n" +
	"\fMoveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"L\n" +
	"\x12CollectLootRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aloot_id\x18\x02 \x01(\tR\x06lootId\"\x88\x01\n" +
	"\x13CollectLootResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x122\n" +
	"\x15new_encrypted_balance\x18\x03 \x01(\tR\x13newEncryptedBalance\"\xc5\x02\n" +
	"\x0fGameStateUpdate\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12+\n" +
	"\x11remaining_seconds\x18\x03 \x01(\rR\x10remainingSeconds\x12&\n" +
	"\aplayers\x18\x04 \x03(\v2\f.game.PlayerR\aplayers\x12-\n" +
	"\n" +
	"loot_items\x18\x05 \x03(\v2\x0e.game.LootItemR\tlootItems\x12\x1d\n" +
	"\x04npcs\x18\x06 \x03(\v2\t.game.NPCR\x04npcs\x12&\n" +
	"\ahazards\x18\a \x03(\v2\f.game.HazardR\ahazards\x12'\n" +
	"\x06events\x18\b \x03(\v2\x0f.game.GameEventR\x06events\"\xd7\x01\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\x12\x16\n" +
	"\x06health\x18\x05 \x01(\x05R\x06health\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05kills\x18\a \x01(\x05R\x05kills\x12\x1a\n" +
	"\btreasure\x18\b \x01(\x05R\btreasure\x12#\n" +
	"\rcharacter_idx\x18\t \x01(\rR\fcharacterIdx\"k\n" +
	"\bLootItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\titem_type\x18\x02 \x01(\tR\bitemType\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"d\n" +
	"\x03NPC\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bnpc_type\x18\x02 \x01(\tR\anpcType\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\x12\x16\n" +
	"\x06health\x18\x05 \x01(\x05R\x06health\"\x8a\x01\n" +
	"\x06Hazard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vhazard_type\x18\x02 \x01(\tR\n" +
	"hazardType\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\x12\x16\n" +
	"\x06radius\x18\x05 \x01(\x02R\x06radius\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\"x\n" +
	"\tGameEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data2?\n" +
	"\vAuthService\x120\n" +
	"\x05Login\x12\x12.game.LoginRequest\x1a\x13.game.LoginResponse2\xd8\x05\n" +
	"\vGameService\x12H\n" +
	"\rCreateSession\x12\x1a.game.CreateSessionRequest\x1a\x1b.game.CreateSessionResponse\x12E\n" +
	"\fListSessions\x12\x19.game.ListSessionsRequest\x1a\x1a.game.ListSessionsResponse\x12B\n" +
	"\vJoinSession\x12\x18.game.JoinSessionRequest\x1a\x19.game.JoinSessionResponse\x12<\n" +
	"\tStartGame\x12\x16.game.StartGameRequest\x1a\x17.game.StartGameResponse\x12:\n" +
	"\n" +
	"WatchLobby\x12\x17.game.WatchLobbyRequest\x1a\x11.game.LobbyUpdate0\x01\x12K\n" +
	"\x0eGetHouseWallet\x12\x1b.game.GetHouseWalletRequest\x1a\x1c.game.GetHouseWalletResponse\x12K\n" +
	"\x0eConfirmDeposit\x12\x1b.game.ConfirmDepositRequest\x1a\x1c.game.ConfirmDepositResponse\x128\n" +
	"\aConnect\x12\x14.game.ConnectRequest\x1a\x15.game.GameStateUpdate0\x01\x12-\n" +
	"\x04Move\x12\x11.game.MoveRequest\x1a\x12.game.MoveResponse\x12B\n" +
	"\vCollectLoot\x12\x18.game.CollectLootRequest\x1a\x19.game.CollectLootResponse\x123\n" +
	"\x06Attack\x12\x13.game.AttackRequest\x1a\x14.game.AttackResponseB*Z(github.com/koded/fog-of-war/server/protob\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_game_proto_goTypes = []any{
	(*LoginRequest)(nil),           // 0: game.LoginRequest
	(*LoginResponse)(nil),          // 1: game.LoginResponse
	(*GetHouseWalletRequest)(nil),  // 2: game.GetHouseWalletRequest
	(*GetHouseWalletResponse)(nil), // 3: game.GetHouseWalletResponse
	(*ConfirmDepositRequest)(nil),  // 4: game.ConfirmDepositRequest
	(*ConfirmDepositResponse)(nil), // 5: game.ConfirmDepositResponse
	(*AttackRequest)(nil),          // 6: game.AttackRequest
	(*AttackResponse)(nil),         // 7: game.AttackResponse
	(*CreateSessionRequest)(nil),   // 8: game.CreateSessionRequest
	(*CreateSessionResponse)(nil),  // 9: game.CreateSessionResponse
	(*SessionInfo)(nil),            // 10: game.SessionInfo
	(*ListSessionsRequest)(nil),    // 11: game.ListSessionsRequest
	(*ListSessionsResponse)(nil),   // 12: game.ListSessionsResponse
	(*JoinSessionRequest)(nil),     // 13: game.JoinSessionRequest
	(*JoinSessionResponse)(nil),    // 14: game.JoinSessionResponse
	(*StartGameRequest)(nil),       // 15: game.StartGameRequest
	(*StartGameResponse)(nil),      // 16: game.StartGameResponse
	(*WatchLobbyRequest)(nil),      // 17: game.WatchLobbyRequest
	(*LobbyPlayer)(nil),            // 18: game.LobbyPlayer
	(*LobbyUpdate)(nil),            // 19: game.LobbyUpdate
	(*ConnectRequest)(nil),         // 20: game.ConnectRequest
	(*MoveRequest)(nil),            // 21: game.MoveRequest
	(*MoveResponse)(nil),           // 22: game.MoveResponse
	(*CollectLootRequest)(nil),     // 23: game.CollectLootRequest
	(*CollectLootResponse)(nil),    // 24: game.CollectLootResponse
	(*GameStateUpdate)(nil),        // 25: game.GameStateUpdate
	(*Player)(nil),                 // 26: game.Player
	(*LootItem)(nil),               // 27: game.LootItem
	(*NPC)(nil),                    // 28: game.NPC
	(*Hazard)(nil),                 // 29: game.Hazard
	(*GameEvent)(nil),              // 30: game.GameEvent
}
var file_game_proto_depIdxs = []int32{
	10, // 0: game.ListSessionsResponse.sessions:type_name -> game.SessionInfo
	18, // 1: game.LobbyUpdate.players:type_name -> game.LobbyPlayer
	26, // 2: game.GameStateUpdate.players:type_name -> game.Player
	27, // 3: game.GameStateUpdate.loot_items:type_name -> game.LootItem
	28, // 4: game.GameStateUpdate.npcs:type_name -> game.NPC
	29, // 5: game.GameStateUpdate.hazards:type_name -> game.Hazard
	30, // 6: game.GameStateUpdate.events:type_name -> game.GameEvent
	0,  // 7: game.AuthService.Login:input_type -> game.LoginRequest
	8,  // 8: game.GameService.CreateSession:input_type -> game.CreateSessionRequest
	11, // 9: game.GameService.ListSessions:input_type -> game.ListSessionsRequest
	13, // 10: game.GameService.JoinSession:input_type -> game.JoinSessionRequest
	15, // 11: game.GameService.StartGame:input_type -> game.StartGameRequest
	17, // 12: game.GameService.WatchLobby:input_type -> game.WatchLobbyRequest
	2,  // 13: game.GameService.GetHouseWallet:input_type -> game.GetHouseWalletRequest
	4,  // 14: game.GameService.ConfirmDeposit:input_type -> game.ConfirmDepositRequest
	20, // 15: game.GameService.Connect:input_type -> game.ConnectRequest
	21, // 16: game.GameService.Move:input_type -> game.MoveRequest
	23, // 17: game.GameService.CollectLoot:input_type -> game.CollectLootRequest
	6,  // 18: game.GameService.Attack:input_type -> game.AttackRequest
	1,  // 19: game.AuthService.Login:output_type -> game.LoginResponse
	9,  // 20: game.GameService.CreateSession:output_type -> game.CreateSessionResponse
	12, // 21: game.GameService.ListSessions:output_type -> game.ListSessionsResponse
	14, // 22: game.GameService.JoinSession:output_type -> game.JoinSessionResponse
	16, // 23: game.GameService.StartGame:output_type -> game.StartGameResponse
	19, // 24: game.GameService.WatchLobby:output_type -> game.LobbyUpdate
	3,  // 25: game.GameService.GetHouseWallet:output_type -> game.GetHouseWalletResponse
	5,  // 26: game.GameService.ConfirmDeposit:output_type -> game.ConfirmDepositResponse
	25, // 27: game.GameService.Connect:output_type -> game.GameStateUpdate
	22, // 28: game.GameService.Move:output_type -> game.MoveResponse
	24, // 29: game.GameService.CollectLoot:output_type -> game.CollectLootResponse
	7,  // 30: game.GameService.Attack:output_type -> game.AttackResponse
	19, // [19:31] is the sub-list for method output_type
	7,  // [7:19] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
