# Generated by Django 5.2.7 on 2025-10-25 23:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('map_type', models.CharField(choices=[('dungeon_alpha', 'Dungeon Alpha'), ('sector_7_ruins', 'Sector 7 Ruins'), ('station_omega', 'Station Omega'), ('jungle_temple', 'Jungle Temple')], max_length=50)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Players'), ('active', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('max_players', models.IntegerField(default=50)),
                ('entry_fee', models.DecimalField(decimal_places=9, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('prize_pool', models.DecimalField(decimal_places=9, default=0, max_digits=18)),
                ('duration_minutes', models.IntegerField(default=5)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encrypted_loot_data', models.TextField(blank=True)),
                ('arcium_session_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('alive', 'Alive'), ('extracted', 'Extracted'), ('eliminated', 'Eliminated')], default='alive', max_length=20)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('health', models.IntegerField(default=100)),
                ('encrypted_loot_balance', models.TextField(blank=True)),
                ('kills', models.IntegerField(default=0)),
                ('entry_transaction_hash', models.CharField(blank=True, max_length=100)),
                ('payout_transaction_hash', models.CharField(blank=True, max_length=100)),
                ('final_payout', models.DecimalField(decimal_places=9, default=0, max_digits=18)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.gamesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game_session')},
            },
        ),
        migrations.CreateModel(
            name='LootItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('small', 'Small Loot'), ('medium', 'Medium Loot'), ('large', 'Large Loot'), ('final_chest', 'Final Chest')], max_length=20)),
                ('sol_value', models.DecimalField(decimal_places=9, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('encrypted_position_x', models.TextField()),
                ('encrypted_position_y', models.TextField()),
                ('arcium_reference', models.CharField(blank=True, max_length=100)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loot_items', to='core.gamesession')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.playersession')),
            ],
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('player_joined', 'Player Joined'), ('player_eliminated', 'Player Eliminated'), ('loot_collected', 'Loot Collected'), ('extraction_success', 'Extraction Success'), ('game_started', 'Game Started'), ('game_ended', 'Game Ended')], max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.gamesession')),
                ('loot_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lootitem')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.playersession')),
                ('target_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_events', to='core.playersession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('entry_fee', 'Entry Fee'), ('payout', 'Payout'), ('transfer', 'Loot Transfer')], max_length=20)),
                ('sol_amount', models.DecimalField(decimal_places=9, max_digits=18)),
                ('transaction_hash', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('game_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gamesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
