# Generated by Django 4.2.23 on 2025-10-27 13:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('npc_type', models.CharField(choices=[('guard', 'Guard'), ('patrol', 'Patrol'), ('sentinel', 'Sentinel')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('patrol_path', models.JSONField(default=list)),
                ('patrol_index', models.IntegerField(default=0)),
                ('speed', models.FloatField(default=1.0)),
                ('health', models.IntegerField(default=100)),
                ('damage', models.IntegerField(default=15)),
                ('detection_range', models.FloatField(default=10.0)),
                ('attack_range', models.FloatField(default=2.0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_move_time', models.DateTimeField(auto_now=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcs', to='core.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hazard_type', models.CharField(choices=[('spike_trap', 'Spike Trap'), ('poison_gas', 'Poison Gas'), ('laser_grid', 'Laser Grid'), ('explosive_barrel', 'Explosive Barrel')], max_length=20)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('radius', models.FloatField(default=3.0)),
                ('damage', models.IntegerField(default=25)),
                ('is_active', models.BooleanField(default=True)),
                ('activation_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=10)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to='core.gamesession')),
            ],
        ),
    ]
